### PR TITLE
added typescript typings

### PR DESCRIPTION
**Pull request by Shadowlauch**
I wanted to use this project in a typescript context so I decided to write typings for it. This makes working with this library in typescript a lot easier.

just iimport via 

`import * as kuroshiro from 'kuroshiro';`

and you are good to go

### CODE REVIEW

**Comment by hexenq** [comment]
Looks good. Thanks.

**Comment by retorquere** [comment]
The typescript definitions are no longer available. Is it possible to reintroduce them? I found them useful.

**Comment by hexenq** [comment]
I'm sorry for that. Since I'm not familiar with typescript, it might take quite a time to get it done. It will be grateful if someone could help with the typings.

**Comment by retorquere** [comment]
I'll give it a try, but I'm not experienced in writing these either.

**Comment by Shadowlauch** [comment]
I haven't used this in a while. Did the interface of the library change, or was the typescript definitions file just not included anymore?

**Comment by hexenq** [comment]
Hello, @Shadowlauch . There is a breaking change in the new major version of kuroshiro. And the interface was changed too. I have removed the definition file for now because I'm not so familiar with typescript.

**Comment by retorquere** [comment]
I think this should do it, but I don't know whether it needs to go in src or in dist:

```
/**
 * Kuroshiro Class
 */
declare class Kuroshiro {
    static Util: {
        isHiragana(str: string): boolean;
        isKatakana(str: string): boolean;
        isKana(str: string): boolean;
        isKanji(str: string): boolean;
        isJapanese(str: string): boolean;
        hasHiragana(str: string): boolean;
        hasKatakana(str: string): boolean;
        hasKana(str: string): boolean;
        hasKanji(str: string): boolean;
        hasJapanese(str: string): boolean;
        kanaToHiragna(str: string): string;
        kanaToKatakana(str: string): string;
        kanaToRomaji(str: string): string;
    };

    /**
     * Constructor
     * @constructs Kuroshiro
     */
    constructor();

    /**
     * Initialize Kuroshiro
     * @memberOf Kuroshiro
     * @instance
     * @returns {Promise} Promise object represents the result of initialization
     */
    init(analyzer: any): Promise<void>;

    /**
     * Convert given string to target syllabary with options available
     * @memberOf Kuroshiro
     * @instance
     * @param {string} str Given String
     * @param {Object} [options] Settings Object
     * @param {string} [options.to="hiragana"] Target syllabary ["hiragana"|"katakana"|"romaji"]
     * @param {string} [options.mode="normal"] Convert mode ["normal"|"spaced"|"okurigana"|"furigana"]
     * @param {string} [options.romajiSystem="hepburn"] Romanization System ["nippon"|"passport"|"hepburn"]
     * @param {string} [options.delimiter_start="("] Delimiter(Start)
     * @param {string} [options.delimiter_end=")"] Delimiter(End)
     * @returns {Promise} Promise object represents the result of conversion
     */

    convert(str: string, options: {
        to?: "hiragana" | "katakana" | "romaji";
        mode?: "normal" | "spaced" | "okurigana" | "furigana";
        romajiSystem?: "nippon" | "passport" | "hepburn";
        delimiter_start?: string;
        delimiter_end?: string;
    }): Promise<string>;
}

export default Kuroshiro;
```

**Comment by hexenq** [comment]
I think it should go to `src/index.d.ts` with `typings` specified in `package.json`.

**Comment by retorquere** [comment]
I still don't know how typescript knows that src/index.d.ts foes with dist/index.js. The above was done by copying core.js to a typescript file, making some changes to haul Util into Kurishiro, and then compiling it.

**Comment by hexenq** [comment]
Isn't `src/index.d.ts ` paired with `src/index.js`? `dist/*` is for browser (umd).

**Comment by retorquere** [comment]
Right, yes, I meant how TS pairs index.d.ts with lib/index.js, which is what a package consumer would use (as per package.json, "main").

**Comment by hexenq** [comment]
> TypeScript will also use a field in package.json named "types" to mirror the purpose of "main" - the compiler will use it to find the “main” definition file to consult.

Referring to [Module Resolution](https://www.typescriptlang.org/docs/handbook/module-resolution.html)

**Comment by osdiab** [comment]
I’m using Kuroshiro now and I have set up TypeScript types for a few libraries before, so I can take a look at this sometime soon :)

**Pull request merged**
